[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[conda]
ignore_base = false

[python]
symbol = "🅟"

[sudo]
disabled = false
symbol = "🅢 "

[git_branch]
symbol = ""

[shell]
# I tend to use fish or powershell, hence I only want the shell to show up when I'm not using either of those (e.g. bash)
disabled=false
fish_indicator = ""
bash_indicator = "bash "
powershell_indicator = ""
format="[$indicator]($style)" # Removed the space after the indicator
